"""Initial migration

Revision ID: 41366b58d13e
Revises: 
Create Date: 2024-10-09 06:41:49.215282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41366b58d13e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=500), nullable=False),
    sa.Column('tipo_pergunta', sa.String(length=20), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('teste_vai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=200), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['slide_id'], ['slide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas')
    op.drop_table('slide')
    op.drop_table('quiz')
    # ### end Alembic commands ###
