"""Criando um db novo

Revision ID: 54cc596f2064
Revises: c6582494eeac
Create Date: 2024-09-03 23:57:49.754393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cc596f2064'
down_revision = 'c6582494eeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('senha', sa.String(length=50), nullable=False),
    sa.Column('tipo_conta', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=26), nullable=False),
    sa.Column('sobrenome', sa.String(length=26), nullable=False),
    sa.Column('usuario', sa.String(length=26), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
