"""Resetei as migrações de novo

Revision ID: 973fc4c06591
Revises: 
Create Date: 2024-10-16 02:40:11.913718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973fc4c06591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco_questoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=500), nullable=False),
    sa.Column('tipo_pergunta', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('bq_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bq_id'], ['banco_questoes.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorioGeral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('jogador', sa.String(length=26), nullable=True),
    sa.Column('pontuacao_total', sa.Integer(), nullable=False),
    sa.Column('tempo_total', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correcao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('correcao', sa.String(length=800), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorioPerguntas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('perguntas_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=300), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['perguntas_id'], ['pergunta.id'], ),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorioGeral.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=300), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    op.drop_table('relatorioPerguntas')
    op.drop_table('correcao')
    op.drop_table('relatorioGeral')
    op.drop_table('pergunta')
    op.drop_table('quiz')
    op.drop_table('banco_questoes')
    # ### end Alembic commands ###
