"""Atualização dos Dados do Users

Revision ID: b2547bbc0064
Revises: 54cc596f2064
Create Date: 2024-09-04 00:16:23.294001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2547bbc0064'
down_revision = '54cc596f2064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nascimento', sa.Date(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=26),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('idade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sobrenome', mysql.VARCHAR(length=26), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=26),
               existing_nullable=False)
        batch_op.drop_column('nascimento')

    # ### end Alembic commands ###
