"""empty message

Revision ID: c6582494eeac
Revises: c0f1006d3bae
Create Date: 2024-09-02 08:09:04.183818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6582494eeac'
down_revision = 'c0f1006d3bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('senha', sa.String(length=50), nullable=False),
    sa.Column('tipo_conta', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=26), nullable=False),
    sa.Column('sobrenome', sa.String(length=26), nullable=False),
    sa.Column('usuario', sa.String(length=26), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
