"""Atualizando a redefinição de senha

Revision ID: e708a3b481a2
Revises: bcba4aff652f
Create Date: 2025-04-22 01:17:34.966780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e708a3b481a2'
down_revision = 'bcba4aff652f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.Column('tipo_conta', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('usuario', sa.String(length=26), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('token_enviado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('banco_questoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=500), nullable=False),
    sa.Column('tipo_pergunta', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bq_id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['bq_id'], ['banco_questoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bq_id')
    )
    op.create_table('relatorioGeral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('jogador', sa.String(length=26), nullable=True),
    sa.Column('pontuacao_total', sa.Integer(), nullable=False),
    sa.Column('tempo_total', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=250), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perguntas_quiz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=300), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correcao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perguntaQuiz_id', sa.Integer(), nullable=False),
    sa.Column('correcao', sa.String(length=800), nullable=False),
    sa.ForeignKeyConstraint(['perguntaQuiz_id'], ['perguntas_quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorioPerguntas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('perguntas_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=300), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['perguntas_id'], ['perguntas_quiz.id'], ),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorioGeral.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorioPerguntas')
    op.drop_table('correcao')
    op.drop_table('resposta')
    op.drop_table('perguntas_quiz')
    op.drop_table('relatorioGeral')
    op.drop_table('perguntas')
    op.drop_table('quiz')
    op.drop_table('banco_questoes')
    op.drop_table('users')
    # ### end Alembic commands ###
