"""Adicionando tabelas novas

Revision ID: ea007258f2d3
Revises: 41366b58d13e
Create Date: 2024-10-09 06:43:26.992666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea007258f2d3'
down_revision = '41366b58d13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slide', schema=None) as batch_op:
        batch_op.drop_column('teste_vai')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste_vai', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
