"""altera nome de correcao_txt para correcao

Revision ID: 7252271c35d3
Revises: 9d6c6fe5722e
Create Date: 2026-05-28 05:53:38.310433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7252271c35d3'
down_revision = '9d6c6fe5722e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correcao', sa.Text(), nullable=True))
        batch_op.drop_column('correcao_txt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correcao_txt', mysql.TEXT(), nullable=True))
        batch_op.drop_column('correcao')

    # ### end Alembic commands ###
