"""adiciona coluna image_path na questao

Revision ID: 9d6c6fe5722e
Revises: eb7924896a68
Create Date: 2026-05-28 05:37:26.854724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6c6fe5722e'
down_revision = 'eb7924896a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
