"""Criando tabela used_tokens

Revision ID: eb7924896a68
Revises: 2718ef4cec55
Create Date: 2026-04-20 18:10:36.320993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7924896a68'
down_revision = '2718ef4cec55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('used_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_used_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_used_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_used_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_used_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_used_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_used_tokens_purpose'))

    op.drop_table('used_tokens')
    # ### end Alembic commands ###
