"""altera nome de correcao_txt para correction e no img tambem

Revision ID: fdec10ec91d7
Revises: 7252271c35d3
Create Date: 2026-05-28 06:06:01.157630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdec10ec91d7'
down_revision = '7252271c35d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('correction_img', sa.String(length=255), nullable=True))
        batch_op.drop_column('correcao_img')
        batch_op.drop_column('correcao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correcao', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('correcao_img', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('correction_img')
        batch_op.drop_column('correction')

    # ### end Alembic commands ###
